function groupBMap() {

        var map = [];
        var relation1 = [];
        relation1.push('物理(二)');
        map['物理(一)'] = relation1;
        var relation2 = [];
        relation2.push('化學(二)');
        map['化學(一)'] = relation2;
        var relation3 = [];
        relation3.push('普通生物(二)');
        map['普通生物(一)'] = relation3;
        var relation4 = [];
        relation4.push('微積分(二)');
        map['微積分(一)'] = relation4;
        var relation5 = [];
        relation5.push('機率');
        relation5.push('微分方程');
        map['微積分(二)'] = relation5;
        var relation6 = [];
        relation6.push('微積分(二)');
        map['線性代數'] = relation6;
        var relation7 = [];
        relation7.push('作業系統概論');
        relation7.push('物件導向程式設計');
        relation7.push('計算機網路概論');
        relation7.push('數位電路設計');
        map['計算機概論與程式設計'] = relation7;
        var relation8 = [];
        relation8.push('資料結構');
        map['物件導向程式設計'] = relation8;
        var relation9 = [];
        relation9.push('正規語言');
        relation9.push('資料結構');
        map['離散數學'] = relation9;
        var relation10 = [];
        relation10.push('編譯器設計概論');
        map['正規語言'] = relation10;
        var relation11 = [];
        relation11.push('軟體工程概論');
        relation11.push('人工智慧');
        map['演算法概論'] = relation11;
        var relation12 = [];
        relation12.push('資訊工程專題(一)');
        relation12.push('編譯器設計概論');
        map['基礎程式設計'] = relation12;
        var relation13 = [];
        relation13.push('資訊工程專題(二)');
        map['資訊工程專題(一)'] = relation13;
        var relation14 = [];
        relation14.push('基礎程式設計');
        relation14.push('資料庫系統概論');
        relation14.push('演算法概論');
        map['資料結構'] = relation14;
        var relation15 = [];
        relation15.push('數位電路實驗');
        map['數位電路設計'] = relation15;
        var relation16 = [];
        relation16.push('計算機組織');
        map['數位電路實驗'] = relation16;
        var relation17 = [];
        relation17.push('微處理機系統實驗');
        map['計算機組織'] = relation17;
        var relation18 = [];
        relation18.push('嵌入式系統設計概論與實作');
        map['微處理機系統實驗'] = relation18;
        var relation19 = [];
        relation19.push('電腦安全概論');
        map['計算機網路概論'] = relation19;
        var relation20 = [];
        relation20.push('密碼學概論');
        map['機率'] = relation20; 
        return map;
        var relation21 = [];
        relation21.push('嵌入式系統設計概論與實作');
        map['作業系統概論'] = relation21;
}


module.exports = groupBMap;

